// Code generated by protoc-gen-go. DO NOT EDIT.
// source: blog/blogpb/blog.proto

/*
Package blogpb is a generated protocol buffer package.

It is generated from these files:
	blog/blogpb/blog.proto

It has these top-level messages:
	Blog
	CreateBlogRequest
	CreateBlogResponse
	ReadBlogRequest
	ReadBlogResponse
	ReadAllBlogRequest
	ReadAllBlogResponse
*/
package blogpb

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import _ "google.golang.org/genproto/googleapis/api/annotations"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Blog struct {
	Id      string `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	Author  string `protobuf:"bytes,2,opt,name=author" json:"author,omitempty"`
	Title   string `protobuf:"bytes,3,opt,name=title" json:"title,omitempty"`
	Content string `protobuf:"bytes,4,opt,name=content" json:"content,omitempty"`
}

func (m *Blog) Reset()                    { *m = Blog{} }
func (m *Blog) String() string            { return proto.CompactTextString(m) }
func (*Blog) ProtoMessage()               {}
func (*Blog) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Blog) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Blog) GetAuthor() string {
	if m != nil {
		return m.Author
	}
	return ""
}

func (m *Blog) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *Blog) GetContent() string {
	if m != nil {
		return m.Content
	}
	return ""
}

type CreateBlogRequest struct {
	Blog *Blog `protobuf:"bytes,1,opt,name=blog" json:"blog,omitempty"`
}

func (m *CreateBlogRequest) Reset()                    { *m = CreateBlogRequest{} }
func (m *CreateBlogRequest) String() string            { return proto.CompactTextString(m) }
func (*CreateBlogRequest) ProtoMessage()               {}
func (*CreateBlogRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *CreateBlogRequest) GetBlog() *Blog {
	if m != nil {
		return m.Blog
	}
	return nil
}

type CreateBlogResponse struct {
	Blog *Blog `protobuf:"bytes,1,opt,name=blog" json:"blog,omitempty"`
}

func (m *CreateBlogResponse) Reset()                    { *m = CreateBlogResponse{} }
func (m *CreateBlogResponse) String() string            { return proto.CompactTextString(m) }
func (*CreateBlogResponse) ProtoMessage()               {}
func (*CreateBlogResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *CreateBlogResponse) GetBlog() *Blog {
	if m != nil {
		return m.Blog
	}
	return nil
}

type ReadBlogRequest struct {
	BlogId string `protobuf:"bytes,1,opt,name=blog_id,json=blogId" json:"blog_id,omitempty"`
}

func (m *ReadBlogRequest) Reset()                    { *m = ReadBlogRequest{} }
func (m *ReadBlogRequest) String() string            { return proto.CompactTextString(m) }
func (*ReadBlogRequest) ProtoMessage()               {}
func (*ReadBlogRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *ReadBlogRequest) GetBlogId() string {
	if m != nil {
		return m.BlogId
	}
	return ""
}

type ReadBlogResponse struct {
	Blog *Blog `protobuf:"bytes,1,opt,name=blog" json:"blog,omitempty"`
}

func (m *ReadBlogResponse) Reset()                    { *m = ReadBlogResponse{} }
func (m *ReadBlogResponse) String() string            { return proto.CompactTextString(m) }
func (*ReadBlogResponse) ProtoMessage()               {}
func (*ReadBlogResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *ReadBlogResponse) GetBlog() *Blog {
	if m != nil {
		return m.Blog
	}
	return nil
}

type ReadAllBlogRequest struct {
	Search string `protobuf:"bytes,1,opt,name=search" json:"search,omitempty"`
	Page   int32  `protobuf:"varint,2,opt,name=page" json:"page,omitempty"`
}

func (m *ReadAllBlogRequest) Reset()                    { *m = ReadAllBlogRequest{} }
func (m *ReadAllBlogRequest) String() string            { return proto.CompactTextString(m) }
func (*ReadAllBlogRequest) ProtoMessage()               {}
func (*ReadAllBlogRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *ReadAllBlogRequest) GetSearch() string {
	if m != nil {
		return m.Search
	}
	return ""
}

func (m *ReadAllBlogRequest) GetPage() int32 {
	if m != nil {
		return m.Page
	}
	return 0
}

type ReadAllBlogResponse struct {
	Blog []*Blog `protobuf:"bytes,1,rep,name=blog" json:"blog,omitempty"`
}

func (m *ReadAllBlogResponse) Reset()                    { *m = ReadAllBlogResponse{} }
func (m *ReadAllBlogResponse) String() string            { return proto.CompactTextString(m) }
func (*ReadAllBlogResponse) ProtoMessage()               {}
func (*ReadAllBlogResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

func (m *ReadAllBlogResponse) GetBlog() []*Blog {
	if m != nil {
		return m.Blog
	}
	return nil
}

func init() {
	proto.RegisterType((*Blog)(nil), "blog.Blog")
	proto.RegisterType((*CreateBlogRequest)(nil), "blog.CreateBlogRequest")
	proto.RegisterType((*CreateBlogResponse)(nil), "blog.CreateBlogResponse")
	proto.RegisterType((*ReadBlogRequest)(nil), "blog.ReadBlogRequest")
	proto.RegisterType((*ReadBlogResponse)(nil), "blog.ReadBlogResponse")
	proto.RegisterType((*ReadAllBlogRequest)(nil), "blog.ReadAllBlogRequest")
	proto.RegisterType((*ReadAllBlogResponse)(nil), "blog.ReadAllBlogResponse")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for BlogService service

type BlogServiceClient interface {
	CreateBlog(ctx context.Context, in *CreateBlogRequest, opts ...grpc.CallOption) (*CreateBlogResponse, error)
	ReadBlog(ctx context.Context, in *ReadBlogRequest, opts ...grpc.CallOption) (*ReadBlogResponse, error)
	ReadAllBlog(ctx context.Context, in *ReadAllBlogRequest, opts ...grpc.CallOption) (*ReadAllBlogResponse, error)
}

type blogServiceClient struct {
	cc *grpc.ClientConn
}

func NewBlogServiceClient(cc *grpc.ClientConn) BlogServiceClient {
	return &blogServiceClient{cc}
}

func (c *blogServiceClient) CreateBlog(ctx context.Context, in *CreateBlogRequest, opts ...grpc.CallOption) (*CreateBlogResponse, error) {
	out := new(CreateBlogResponse)
	err := grpc.Invoke(ctx, "/blog.BlogService/CreateBlog", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *blogServiceClient) ReadBlog(ctx context.Context, in *ReadBlogRequest, opts ...grpc.CallOption) (*ReadBlogResponse, error) {
	out := new(ReadBlogResponse)
	err := grpc.Invoke(ctx, "/blog.BlogService/ReadBlog", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *blogServiceClient) ReadAllBlog(ctx context.Context, in *ReadAllBlogRequest, opts ...grpc.CallOption) (*ReadAllBlogResponse, error) {
	out := new(ReadAllBlogResponse)
	err := grpc.Invoke(ctx, "/blog.BlogService/ReadAllBlog", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for BlogService service

type BlogServiceServer interface {
	CreateBlog(context.Context, *CreateBlogRequest) (*CreateBlogResponse, error)
	ReadBlog(context.Context, *ReadBlogRequest) (*ReadBlogResponse, error)
	ReadAllBlog(context.Context, *ReadAllBlogRequest) (*ReadAllBlogResponse, error)
}

func RegisterBlogServiceServer(s *grpc.Server, srv BlogServiceServer) {
	s.RegisterService(&_BlogService_serviceDesc, srv)
}

func _BlogService_CreateBlog_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateBlogRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BlogServiceServer).CreateBlog(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/blog.BlogService/CreateBlog",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BlogServiceServer).CreateBlog(ctx, req.(*CreateBlogRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BlogService_ReadBlog_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReadBlogRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BlogServiceServer).ReadBlog(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/blog.BlogService/ReadBlog",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BlogServiceServer).ReadBlog(ctx, req.(*ReadBlogRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BlogService_ReadAllBlog_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReadAllBlogRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BlogServiceServer).ReadAllBlog(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/blog.BlogService/ReadAllBlog",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BlogServiceServer).ReadAllBlog(ctx, req.(*ReadAllBlogRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _BlogService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "blog.BlogService",
	HandlerType: (*BlogServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateBlog",
			Handler:    _BlogService_CreateBlog_Handler,
		},
		{
			MethodName: "ReadBlog",
			Handler:    _BlogService_ReadBlog_Handler,
		},
		{
			MethodName: "ReadAllBlog",
			Handler:    _BlogService_ReadAllBlog_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "blog/blogpb/blog.proto",
}

func init() { proto.RegisterFile("blog/blogpb/blog.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 374 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x52, 0xbb, 0x4e, 0xeb, 0x40,
	0x10, 0xbd, 0x71, 0x1c, 0x27, 0x77, 0x22, 0xdd, 0x0b, 0x03, 0x38, 0x8e, 0x41, 0x08, 0x5c, 0x21,
	0x8a, 0x58, 0x24, 0x50, 0xd1, 0x90, 0x50, 0xd1, 0x9a, 0x8e, 0x02, 0xb4, 0xb1, 0x47, 0x8e, 0x25,
	0xe3, 0x35, 0xf6, 0x26, 0x42, 0x42, 0x34, 0xfc, 0x02, 0x9f, 0xc6, 0x2f, 0xf0, 0x09, 0x7c, 0x00,
	0xf2, 0x6e, 0x1e, 0xce, 0x43, 0x82, 0xc6, 0xde, 0x73, 0xe6, 0xcc, 0x9c, 0x9d, 0xa3, 0x05, 0x73,
	0x18, 0xf3, 0xd0, 0x2d, 0x3e, 0xe9, 0x50, 0xfe, 0x3a, 0x69, 0xc6, 0x05, 0x47, 0xbd, 0x38, 0xdb,
	0x07, 0x21, 0xe7, 0x61, 0x4c, 0x2e, 0x4b, 0x23, 0x97, 0x25, 0x09, 0x17, 0x4c, 0x44, 0x3c, 0xc9,
	0x95, 0xc6, 0xb9, 0x07, 0x7d, 0x10, 0xf3, 0x10, 0xff, 0x81, 0x16, 0x05, 0x56, 0xe5, 0xa8, 0x72,
	0xf2, 0xd7, 0xd3, 0xa2, 0x00, 0x4d, 0x30, 0xd8, 0x58, 0x8c, 0x78, 0x66, 0x69, 0x92, 0x9b, 0x22,
	0xdc, 0x85, 0x9a, 0x88, 0x44, 0x4c, 0x56, 0x55, 0xd2, 0x0a, 0xa0, 0x05, 0x75, 0x9f, 0x27, 0x82,
	0x12, 0x61, 0xe9, 0x92, 0x9f, 0x41, 0xa7, 0x07, 0xdb, 0xd7, 0x19, 0x31, 0x41, 0x85, 0x8b, 0x47,
	0x4f, 0x63, 0xca, 0x05, 0x1e, 0x82, 0xbc, 0x9a, 0xb4, 0x6b, 0x76, 0xa1, 0x23, 0xef, 0x2c, 0x05,
	0x92, 0x77, 0xce, 0x01, 0xcb, 0x4d, 0x79, 0xca, 0x93, 0x9c, 0x7e, 0xec, 0x3a, 0x85, 0xff, 0x1e,
	0xb1, 0xa0, 0x6c, 0xd4, 0x82, 0x7a, 0x51, 0x7a, 0x98, 0xaf, 0x66, 0x14, 0xf0, 0x26, 0x70, 0xba,
	0xb0, 0xb5, 0xd0, 0xfe, 0x72, 0xfe, 0x15, 0x60, 0xd1, 0xd3, 0x8f, 0xe3, 0xb2, 0x85, 0x09, 0x46,
	0x4e, 0x2c, 0xf3, 0x47, 0x33, 0x07, 0x85, 0x10, 0x41, 0x4f, 0x59, 0x48, 0x32, 0xbe, 0x9a, 0x27,
	0xcf, 0xce, 0x05, 0xec, 0x2c, 0x4d, 0x58, 0x33, 0xae, 0x6e, 0x32, 0xee, 0x7e, 0x55, 0xa0, 0x59,
	0xc0, 0x5b, 0xca, 0x26, 0x91, 0x4f, 0xd8, 0x07, 0x58, 0xc4, 0x83, 0x2d, 0xa5, 0x5f, 0x4b, 0xd9,
	0xb6, 0xd6, 0x0b, 0xca, 0xd0, 0xf9, 0x83, 0x97, 0xd0, 0x98, 0xed, 0x8f, 0x7b, 0x4a, 0xb7, 0x92,
	0x9d, 0x6d, 0xae, 0xd2, 0xf3, 0x66, 0x82, 0x66, 0x69, 0x0d, 0xb4, 0x16, 0xc2, 0xe5, 0x6c, 0xec,
	0xf6, 0x86, 0xca, 0x74, 0xca, 0xf1, 0xdb, 0xc7, 0xe7, 0xbb, 0xb6, 0x8f, 0x6d, 0x77, 0x72, 0xe6,
	0xd2, 0x33, 0x7b, 0x4c, 0x63, 0x72, 0xc9, 0x1f, 0x71, 0xf7, 0x45, 0x05, 0xf8, 0x3a, 0x68, 0xdc,
	0x19, 0xea, 0x4d, 0x0f, 0x0d, 0xf9, 0x56, 0x7b, 0xdf, 0x01, 0x00, 0x00, 0xff, 0xff, 0x0e, 0xad,
	0xde, 0x75, 0xe9, 0x02, 0x00, 0x00,
}
